server:
  port: 8083
spring:
  application:
    name: backend
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/FallDetection?useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: holmes96
    # password: 12345
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      password: holmes96
      lettuce:
        pool:
          max-active: 10
          max-idle: 10
          min-idle: 1
          time-between-eviction-runs: 10s
  # WebFlux配置
  webflux:
    base-path: /

  # 编解码器配置
  codec:
    max-in-memory-size: 10MB

mybatis-plus:
  type-aliases-package: com.falldetection.backend.entity # 别名扫描包

# Qwen模型配置 - 注意这里的配置结构
qwen:
  # API密钥配置 - 优先从环境变量获取，如果没有则使用默认值(需要替换)
  api-key: sk-14ad107ba9cd45d2bd605a4b3655ce91
  # API基础URL
  base-url: https://dashscope.aliyuncs.com/compatible-mode/v1
  # 模型名称
  model-name: qwen-max
  # 温度参数
  temperature: 0.7
  # 最大token数
  max-tokens: 2000

iflytek:
  appid: 72a88d29
  apikey: f0712c7d093953bf66dcec2e975e3396
  host: https://iat.cn-huabei-1.xf-yun.com/v1
  secretKey: MGFkYzI2Yjc3YjBiOTg5NGM0NGI4YzM1